services:
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  
  bot:
    build: .
    env_file:
      - ./.env
    container_name: money_bot
    ports:
      - '8001:8001'
    # depends_on:
    #   - ngrok
    command: sh -c 'python main.py'
    networks:
      - bot_network
    logging:
      driver: "json-file"
      options:
          max-size: "20m"

networks:
  bot_network:
    name: django_fastapi_common-network
    external: true